### ISSUE TITLE
docker builds appear to be failing

### ISSUE THREAD

**Issue by Wildcarde** [steffendx/GoNorth#27]
I'm trying to rehome my laptop install of gonorth to a server so I can use it less tethered to one machine but am running into issues. I've tried cloning over the gonorth install from my laptop and rebuilding with that i end up with the below but am allowed to login (all data appears to be missing however):
```
sudo docker-compose up
Creating mongodb ... done
Creating gonorthlaptop_web_1 ... done
Attaching to mongodb, gonorthlaptop_web_1
web_1      | warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
web_1      |       No XML encryptor configured. Key {04d4c90c-d6dc-4b55-bfa0-6c40efb0afff} may be persisted to storage in unencrypted form.
web_1      | Hosting environment: Production
web_1      | Content root path: /app
web_1      | Now listening on: http://[::]:80
web_1      | Application started. Press Ctrl+C to shut down.
web_1      | fail: Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery[7]
web_1      |       An exception was thrown while deserializing the token.
web_1      | System.InvalidOperationException: The antiforgery token could not be decrypted. ---> System.Security.Cryptography.CryptographicException: The key {bdcb965b-99ac-4e9b-836e-b81d840227bc} was not found in the key ring.
web_1      |    at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
web_1      |    at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
web_1      |    at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
web_1      |    at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
web_1      |    --- End of inner exception stack trace ---
web_1      |    at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
web_1      |    at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)
```

If I try to start from scratch and just copy over the dbdata i get a much longer series of errors:
```
GoNorth]$ sudo docker-compose up
Creating mongodb ... done
Creating gonorth_web_1 ... done
Attaching to mongodb, gonorth_web_1
web_1      | warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
web_1      |       No XML encryptor configured. Key {6a1b47d2-7348-42b8-9689-2fb2b1e720c9} may be persisted to storage in unencrypted form.
web_1      | Hosting environment: Production
web_1      | Content root path: /app
web_1      | Now listening on: http://[::]:80
web_1      | Application started. Press Ctrl+C to shut down.
web_1      | fail: Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery[7]
web_1      |       An exception was thrown while deserializing the token.
web_1      | System.InvalidOperationException: The antiforgery token could not be decrypted. ---> System.Security.Cryptography.CryptographicException: The key {04d4c90c-d6dc-4b55-bfa0-6c40efb0afff} was not found in the key ring.
web_1      |    at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
web_1      |    at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
web_1      |    at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
web_1      |    at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
web_1      |    --- End of inner exception stack trace ---
web_1      |    at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
web_1      |    at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)
web_1      | fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[0]
web_1      |       An unhandled exception has occurred: A timeout occured after 30000ms selecting a server using CompositeServerSelector{ Selectors = MongoDB.Driver.MongoClient+AreSessionsSupportedServerSelector, LatencyLimitingServerSelector{ AllowedLatencyRange = 00:00:00.0150000 } }. Client view of cluster state is { ClusterId : "1", ConnectionMode : "Automatic", Type : "Unknown", State : "Disconnected", Servers : [{ ServerId: "{ ClusterId : 1, EndPoint : "Unspecified/mongo:27017" }", EndPoint: "Unspecified/mongo:27017", State: "Disconnected", Type: "Unknown", HeartbeatException: "MongoDB.Driver.MongoConnectionException: An exception occurred while opening a connection to the server. ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: No such device or address
web_1      |          at System.Net.Dns.InternalGetHostByName(String hostName, Boolean includeIPv6)
web_1      |          at System.Net.Dns.ResolveCallback(Object context)
web_1      |       --- End of stack trace from previous location where exception was thrown ---
web_1      |          at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
web_1      |          at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
web_1      |          at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
web_1      |          at System.Net.Dns.<>c.<GetHostAddressesAsync>b__25_1(IAsyncResult asyncResult)
web_1      |          at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
web_1      |       --- End of stack trace from previous location where exception was thrown ---
web_1      |          at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
web_1      |          at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
web_1      |          at MongoDB.Driver.Core.Connections.TcpStreamFactory.<ResolveEndPointsAsync>d__10.MoveNext()
web_1      |       --- End of stack trace from previous location where exception was thrown ---
web_1      |          at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
web_1      |          at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
web_1      |          at MongoDB.Driver.Core.Connections.TcpStreamFactory.<CreateStreamAsync>d__4.MoveNext()
web_1      |       --- End of stack trace from previous location where exception was thrown ---
web_1      |          at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
web_1      |          at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
web_1      |          at MongoDB.Driver.Core.Connections.BinaryConnection.<OpenHelperAsync>d__48.MoveNext()
web_1      |          --- End of inner exception stack trace ---
web_1      |          at MongoDB.Driver.Core.Connections.BinaryConnection.<OpenHelperAsync>d__48.MoveNext()
web_1      |       --- End of stack trace from previous location where exception was thrown ---
web_1      |          at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
web_1      |          at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
web_1      |          at MongoDB.Driver.Core.Servers.ServerMonitor.<HeartbeatAsync>d__27.MoveNext()" }] }.
web_1      | System.TimeoutException: A timeout occured after 30000ms selecting a server using CompositeServerSelector{ Selectors = MongoDB.Driver.MongoClient+AreSessionsSupportedServerSelector, LatencyLimitingServerSelector{ AllowedLatencyRange = 00:00:00.0150000 } }. Client view of cluster state is { ClusterId : "1", ConnectionMode : "Automatic", Type : "Unknown", State : "Disconnected", Servers : [{ ServerId: "{ ClusterId : 1, EndPoint : "Unspecified/mongo:27017" }", EndPoint: "Unspecified/mongo:27017", State: "Disconnected", Type: "Unknown", HeartbeatException: "MongoDB.Driver.MongoConnectionException: An exception occurred while opening a connection to the server. ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: No such device or address
web_1      |    at System.Net.Dns.InternalGetHostByName(String hostName, Boolean includeIPv6)
web_1      |    at System.Net.Dns.ResolveCallback(Object context)
web_1      | --- End of stack trace from previous location where exception was thrown ---
web_1      |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
web_1      |    at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
web_1      |    at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
web_1      |    at System.Net.Dns.<>c.<GetHostAddressesAsync>b__25_1(IAsyncResult asyncResult)
web_1      |    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
web_1      | --- End of stack trace from previous location where exception was thrown ---
web_1      |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
web_1      |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
web_1      |    at MongoDB.Driver.Core.Connections.TcpStreamFactory.<ResolveEndPointsAsync>d__10.MoveNext()
web_1      | --- End of stack trace from previous location where exception was thrown ---
web_1      |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
web_1      |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
web_1      |    at MongoDB.Driver.Core.Connections.TcpStreamFactory.<CreateStreamAsync>d__4.MoveNext()
web_1      | --- End of stack trace from previous location where exception was thrown ---
web_1      |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
web_1      |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
web_1      |    at MongoDB.Driver.Core.Connections.BinaryConnection.<OpenHelperAsync>d__48.MoveNext()
web_1      |    --- End of inner exception stack trace ---
web_1      |    at MongoDB.Driver.Core.Connections.BinaryConnection.<OpenHelperAsync>d__48.MoveNext()
web_1      | --- End of stack trace from previous location where exception was thrown ---
web_1      |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
web_1      |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
web_1      |    at MongoDB.Driver.Core.Servers.ServerMonitor.<HeartbeatAsync>d__27.MoveNext()" }] }.
web_1      |    at MongoDB.Driver.Core.Clusters.Cluster.ThrowTimeoutException(IServerSelector selector, ClusterDescription description)
web_1      |    at MongoDB.Driver.Core.Clusters.Cluster.WaitForDescriptionChangedHelper.HandleCompletedTask(Task completedTask)
web_1      |    at MongoDB.Driver.Core.Clusters.Cluster.<WaitForDescriptionChangedAsync>d__50.MoveNext()
web_1      | --- End of stack trace from previous location where exception was thrown ---
web_1      |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
web_1      |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
web_1      |    at MongoDB.Driver.Core.Clusters.Cluster.<SelectServerAsync>d__43.MoveNext()
web_1      | --- End of stack trace from previous location where exception was thrown ---
web_1      |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
web_1      |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
web_1      |    at MongoDB.Driver.MongoClient.<AreSessionsSupportedAfterSeverSelctionAsync>d__37.MoveNext()
web_1      | --- End of stack trace from previous location where exception was thrown ---
web_1      |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
web_1      |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
web_1      |    at MongoDB.Driver.MongoClient.<AreSessionsSupportedAsync>d__34.MoveNext()
web_1      | --- End of stack trace from previous location where exception was thrown ---
web_1      |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
web_1      |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
web_1      |    at MongoDB.Driver.MongoClient.<StartImplicitSessionAsync>d__26.MoveNext()
web_1      | --- End of stack trace from previous location where exception was thrown ---
web_1      |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
web_1      |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
web_1      |    at MongoDB.Driver.MongoCollectionImpl`1.<UsingImplicitSessionAsync>d__91`1.MoveNext()
web_1      | --- End of stack trace from previous location where exception was thrown ---
web_1      |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
web_1      |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
web_1      |    at MongoDB.Driver.IAsyncCursorSourceExtensions.<FirstOrDefaultAsync>d__5`1.MoveNext()
web_1      | --- End of stack trace from previous location where exception was thrown ---
web_1      |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
web_1      |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
web_1      |    at GoNorth.Data.User.UserMongoDbAccess.<GetUserByNormalizedUserName>d__6.MoveNext() in /app/Data/User/UserMongoDbAccess.cs:line 80
web_1      | --- End of stack trace from previous location where exception was thrown ---
web_1      |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
web_1      |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
web_1      |    at GoNorth.Authentication.GoNorthUserStore.<FindByNameAsync>d__7.MoveNext() in /app/Authentication/GoNorthUserStore.cs:line 96
web_1      | --- End of stack trace from previous location where exception was thrown ---
web_1      |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
web_1      |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
web_1      |    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
web_1      |    at Microsoft.AspNetCore.Identity.SignInManager`1.<PasswordSignInAsync>d__34.MoveNext()
web_1      | --- End of stack trace from previous location where exception was thrown ---
web_1      |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
web_1      |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
web_1      |    at GoNorth.Controllers.AccountController.<Login>d__14.MoveNext() in /app/Controllers/AccountController.cs:line 132
web_1      | --- End of stack trace from previous location where exception was thrown ---
web_1      |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
web_1      |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
web_1      |    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
web_1      |    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
web_1      | --- End of stack trace from previous location where exception was thrown ---
web_1      |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
web_1      |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
web_1      |    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
web_1      | --- End of stack trace from previous location where exception was thrown ---
web_1      |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
web_1      |    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
web_1      |    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
web_1      |    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
web_1      | --- End of stack trace from previous location where exception was thrown ---
web_1      |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
web_1      |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
web_1      |    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
web_1      | --- End of stack trace from previous location where exception was thrown ---
web_1      |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
web_1      |    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
web_1      |    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
web_1      |    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
web_1      | --- End of stack trace from previous location where exception was thrown ---
web_1      |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
web_1      |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
web_1      |    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
web_1      | --- End of stack trace from previous location where exception was thrown ---
web_1      |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
web_1      |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
web_1      |    at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
web_1      | --- End of stack trace from previous location where exception was thrown ---
web_1      |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
web_1      |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
web_1      |    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
web_1      | --- End of stack trace from previous location where exception was thrown ---
web_1      |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
web_1      |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
web_1      |    at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.<Invoke>d__4.MoveNext()
web_1      | --- End of stack trace from previous location where exception was thrown ---
web_1      |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
web_1      |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
web_1      |    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()
^CGracefully stopping... (press Ctrl+C again to force)
Stopping gonorth_web_1 ... done
Stopping mongodb       ... done
```

Any thoughts on how to get this working?

**Comment by steffendx** [comment]
The second, longer error message seems like GoNorth can not connect to the MongoDB.  
I will try and reproduce the first error message as well and get back to you as soon as I know more regarding this problem.
