### ISSUE TITLE
Antiforgery deserialization token error

### ISSUE THREAD

**Issue by MrDienns** [steffendx/GoNorth#52]
After updating to the latest release (1.8.1.0), I'm seeing this error in the console, and it might explain why the map and quest page is empty for me. I don't see anything specifically mentioned in the update log. Did I miss anything?

```fail: Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery[7]
      An exception was thrown while deserializing the token.
      Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery token could not be decrypted.
       ---> System.Security.Cryptography.CryptographicException: The key {3f9a4971-7bcb-4458-a3a7-bfb6ca1b6644} was not found in the key ring.
         at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
         at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
         at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
         at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
         --- End of inner exception stack trace ---
         at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
         at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)```

**Comment by steffendx** [comment]
This issue did not occure for me. I will check what possible the reason might be.

Did you clear the cache / reloaded the page using ctrl+f5 just to make sure no JavaScript is cached?
Did you login again or did you use a saved login?

**Comment by MrDienns** [comment]
Thanks for the quick relpy. I've purged the cache in Cloudflare (not sure if there was any). I also tried to log into GoNorth via an incognito Firefox tab; so fresh login, and presumably no caches.

I do notice two Javascript errors in the console:

<img width="1118" alt="image" src="https://user-images.githubusercontent.com/15938901/104857224-3c8e2300-5917-11eb-915b-d929e0789564.png">

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/15938901/104857231-4e6fc600-5917-11eb-91c4-ed438ecbee93.png">

**Comment by steffendx** [comment]
That seems like a cache issue.

This might seem like a stupid question, but you also restarted the server after replacing the files correct?

**Comment by MrDienns** [comment]
I'm running on Kubernetes, so virtually the only way to update is to destroy the current pod and spin up a new one. The following directories are persisted:

```
/app/MapImages
/app/NpcImages
/app/KirjaFiles
/app/ItemImages
/app/TaskImages
/app/SkillImages
```

**Comment by MrDienns** [comment]
Oh, I think it works now. I think Cloudflare still had some cache, for whatever reason. I've turned on development mode in Cloudflare and now the pages load for me. I also don't see the error in the console anymore. Not sure how Cloudflare still had cache, after I literally purged it.

**Comment by steffendx** [comment]
Awesome! Glad to hear that it works now. Hopefully the new features will be useful.
